// <auto-generated />
using MVC_Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Web.Migrations
{
    [DbContext(typeof(SD19312DbContext))]
    partial class SD19312DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_Web.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayOrder = 1,
                            Name = "Hung"
                        },
                        new
                        {
                            ID = 2,
                            DisplayOrder = 9,
                            Name = "Banh"
                        },
                        new
                        {
                            ID = 3,
                            DisplayOrder = 5,
                            Name = "Keo"
                        },
                        new
                        {
                            ID = 4,
                            DisplayOrder = 8,
                            Name = "Khoai"
                        },
                        new
                        {
                            ID = 5,
                            DisplayOrder = 5,
                            Name = "Dua hau"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
